"""initial

Revision ID: f3574a5b4062
Revises: 
Create Date: 2024-12-27 17:43:05.840651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f3574a5b4062'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_symbols',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('fullName', sa.VARCHAR(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('ix_exchange_rate_symbols_symbol', 'exchange_rate_symbols', ['symbol'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('userId', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('transactionDate', sa.DATETIME(), nullable=True),
    sa.Column('createdBy', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('transactionType', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_transactionType', 'transactions', ['transactionType'], unique=False)
    op.create_index('ix_transactions_transactionDate', 'transactions', ['transactionDate'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_category', 'transactions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('fullName', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('scopes', sa.VARCHAR(), nullable=True),
    sa.Column('firstLogin', sa.BOOLEAN(), nullable=True),
    sa.Column('createdBy', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emailAddress')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('base', sa.VARCHAR(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('rates', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['base'], ['exchange_rate_symbols.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exchange_rates_id', 'exchange_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###