"""fields change in transactions

Revision ID: f5aa9b51c88b
Revises: 8fd4f99175ba
Create Date: 2024-12-24 22:35:08.944409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5aa9b51c88b"
down_revision: Union[str, None] = "8fd4f99175ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("transactionDate", sa.DateTime(), nullable=False),
        sa.Column(
            "transactionType",
            sa.String(),
            nullable=False,
            default="expense",
        ),
        sa.Column("userId", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("createdBy", sa.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["createdBy"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_category"), "transactions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_transaction_type"),
        "transactions",
        ["transactionType"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_transaction_date"),
        "transactions",
        ["transactionDate"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_transaction_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
